[Unit]
Description=
Description=Logitech Configuration Daemon
StartLimitIntervalSec=0
After=
After=local-fs.target lightdm.service
Wants=

[Service]
ExecStart=
ExecStart=/usr/local/bin/logid-wrapper.py

[Install]
WantedBy=
