- name: Install logiops
  hosts: localhost
  connection: local
  vars:
    systemd: /etc/systemd/system
  vars_files: vars/shared.yml
  become: true
  tasks:

    - name: Systemd override logid directory
      ansible.builtin.file:
        state: directory
        path: "{{ systemd }}/logid.service.d"

    - name: Systemd override logid service
      ansible.builtin.copy:
        src: files/logid.conf
        dest: "{{ systemd }}/logid.service.d/override.conf"

    - name: Logid wrapper
      ansible.builtin.template:
        src: templates/logid-wrapper.py.j2
        dest: /usr/local/bin/logid-wrapper.py
        mode: 0755

    - name: Logid gesture configuration
      ansible.builtin.template:
        src: templates/logid.cfg.j2
        dest: /etc/logid.cfg

    - name: Solaar service
      ansible.builtin.copy:
        src: files/solaar.service
        dest: "{{ systemd }}/solaar.service"

    - name: Solaar desktop file directory
      ansible.builtin.file:
        state: directory
        path: "{{ ansible_facts.user_dir }}/.config/autostart"

    - name: Solaar desktop file
      ansible.builtin.copy:
        src: files/solaar.desktop
        dest: "{{ ansible_facts.user_dir }}/.config/autostart"

    # needs to reload files I copied
    - name: Enable Solaar
      ansible.builtin.systemd:
        name: solaar
        enabled: true
        state: started
        daemon-reload: true

    - name: USB receiver udev rule
      ansible.builtin.template:
        src: templates/99-logid.rules.j2
        dest: /etc/udev/rules.d/99-logid.rules

